name: GCR Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    deploy:
        name: Setup GCloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
        steps:
        - name: Login
          uses: google-github-actions/setup-gcloud@main
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_email: ${{ secrets.GCP_EMAIL }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Token replacement
          uses: microsoft/variable-substitution@v1 
          with:
              files: '**/appsettings.json'
          env:
              "Sendgrid.ApiKey": ${{ secrets.SENDGRID_APIKEY }}
              "GoogleCloud.ProjectId": ${{ secrets.GCP_PROJECT_ID }}
              "GoogleCloud.DefaultStorageBucket": ${{ secrets.GCP_DEFAULT_STORAGE_BUCKET}}
              "GoogleCloud.DataLocation": ${{ secrets.GCP_DEFAULT_LOCATION }}
              "GoogleCloud.StorageClass": ${{ secrets.GCP_STORAGE_CLASS }}

        - name: Build Docker image
          run: docker build -f ./Web/PersonalWebsiteBE/Dockerfile -t $IMAGE_NAME .

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region australia-southeast1 --platform managed