name: GCR Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        
        env:
          REGISTRY: us-central1-docker.pkg.dev
          IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}/personal.api
          
        permissions:
          contents: 'read'
          id-token: 'write'

        steps:
        - uses: actions/checkout@v3

        - id: 'auth'
          name: "Authenticate Google Cloud"
          uses: 'google-github-actions/auth@v1'
          with:
            workload_identity_provider: ${{secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
            service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

        - name: Token replacement
          uses: receiptably/variable-substitution@v1
          with:
              files: '**/appsettings.json'
          env:
              "Sendgrid.ApiKey": ${{ secrets.SENDGRID_APIKEY }}
              "GoogleCloud.ProjectId": ${{ secrets.GCP_PROJECT_ID }}
              "GoogleCloud.DefaultStorageBucket": ${{ secrets.GCP_DEFAULT_STORAGE_BUCKET}}
              "GoogleCloud.DataLocation": ${{ secrets.GCP_DEFAULT_LOCATION }}
              "GoogleCloud.StorageClass": ${{ secrets.GCP_STORAGE_CLASS }}

        - name: Configure Google Cloud
          uses: google-github-actions/setup-gcloud@v1

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet $REGISTRY

        - name: Build Docker image
          run: docker build -f ./Web/PersonalWebsiteBE/Dockerfile -t $IMAGE_NAME .

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy personal-website-api --image $IMAGE_NAME --region us-central1 --platform managed