name: GCR Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    deploy:
        name: Setup GCloud Account
        runs-on: ubuntu-latest
        
        env:
          REGISTRY: us-east1-docker.pkg.dev
          IMAGE_NAME: us-central1-docker.pkg.dev/personal-313620/personalapi/personal.api
          
        permissions:
          contents: 'read'
          id-token: 'write'

        steps:
        - uses: actions/checkout@v3

        - id: 'auth'
          name: "Authenticate Google Cloud"
          uses: 'google-github-actions/auth@v1'
          with:
            workload_identity_provider: 'projects/822547401103/locations/global/workloadIdentityPools/github-actions/providers/personal-identity-pool-github'
            service_account: github-actions@personal-313620.iam.gserviceaccount.com

        - name: Token replacement
          uses: receiptably/variable-substitution@v1
          with:
              files: '**/appsettings.json'
          env:
              "Sendgrid.ApiKey": ${{ secrets.SENDGRID_APIKEY }}
              "GoogleCloud.ProjectId": ${{ secrets.GCP_PROJECT_ID }}
              "GoogleCloud.DefaultStorageBucket": ${{ secrets.GCP_DEFAULT_STORAGE_BUCKET}}
              "GoogleCloud.DataLocation": ${{ secrets.GCP_DEFAULT_LOCATION }}
              "GoogleCloud.StorageClass": ${{ secrets.GCP_STORAGE_CLASS }}

        - name: Configure Google Cloud
          uses: google-github-actions/setup-gcloud@v1

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet $REGISTRY

        - name: Build Docker image
          run: docker build -f ./Web/PersonalWebsiteBE/Dockerfile -t $IMAGE_NAME .

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy personal-website-api --image $IMAGE_NAME --region us-central1 --platform managed